import logging
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from app.core.security import get_current_user
from app.db.database import get_db
from bson import ObjectId
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from io import BytesIO
from datetime import datetime

logger = logging.getLogger("healthsense.report")
router = APIRouter(tags=["Reports"])


@router.post("/report/generate")
async def generate_report(
    payload: dict,
    user_id: str = Depends(get_current_user),
):
    prediction_id = payload.get("prediction_id")
    if not prediction_id:
        raise HTTPException(400, "prediction_id is required.")

    # MED-02: Safe ObjectId conversion — prevents 500 crash on malformed IDs
    if not ObjectId.is_valid(prediction_id):
        raise HTTPException(400, "Invalid prediction_id format.")

    db = get_db()
    pred = await db.predictions.find_one({"_id": ObjectId(prediction_id), "user_id": user_id})
    if not pred:
        raise HTTPException(404, "Prediction not found.")

    user_query = {"_id": ObjectId(user_id)} if ObjectId.is_valid(user_id) else {"email": user_id}
    user = await db.users.find_one(user_query)

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("Title", parent=styles["Heading1"],
                                  textColor=colors.HexColor("#0A1628"), fontSize=20)
    heading_style = ParagraphStyle("Heading", parent=styles["Heading2"],
                                    textColor=colors.HexColor("#2563EB"), fontSize=13)
    body_style = styles["BodyText"]
    disclaimer_style = ParagraphStyle("Disclaimer", parent=styles["BodyText"],
                                       textColor=colors.grey, fontSize=8)

    story = []
    story.append(Paragraph("HealthSense AI — Prediction Report", title_style))
    story.append(Paragraph(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", body_style))
    story.append(Spacer(1, 0.4 * cm))

    # Patient info
    story.append(Paragraph("Patient Profile", heading_style))
    patient_data = [
        ["Name", user.get("name", "N/A")],
        ["Age", str(user.get("age") or "N/A")],
        ["Gender", user.get("gender") or "N/A"],
        ["Blood Type", user.get("blood_type") or "N/A"],
    ]
    t = Table(patient_data, colWidths=[5 * cm, 12 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#EFF6FF")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#1E40AF")),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.4 * cm))

    # Prediction result
    story.append(Paragraph("Prediction Result", heading_style))
    result_color = "#EF4444" if pred["result"] == "positive" else "#10B981"
    story.append(Paragraph(
        f"Disease: <b>{pred['disease'].replace('_', ' ').title()}</b> | "
        f"Result: <font color='{result_color}'><b>{pred['result'].upper()}</b></font> | "
        f"Probability: <b>{pred['probability']}%</b> | "
        f"Confidence: <b>{pred['confidence'].upper()}</b>",
        body_style,
    ))
    story.append(Spacer(1, 0.3 * cm))

    # Inputs table
    story.append(Paragraph("Input Parameters", heading_style))
    input_rows = [["Parameter", "Value"]] + [
        [k.replace("_", " ").title(), str(v)] for k, v in pred["inputs"].items()
    ]
    inp_table = Table(input_rows, colWidths=[8 * cm, 9 * cm])
    inp_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0A1628")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("PADDING", (0, 0), (-1, -1), 6),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
    ]))
    story.append(inp_table)
    story.append(Spacer(1, 0.4 * cm))

    # SHAP
    shap = pred.get("shap_values", {})
    if shap:
        story.append(Paragraph("Top Contributing Factors (SHAP)", heading_style))
        for feat, pct in shap.items():
            story.append(Paragraph(f"• {feat.replace('_', ' ').title()}: {pct}% contribution", body_style))
        story.append(Spacer(1, 0.4 * cm))

    # Disclaimer
    story.append(Spacer(1, 1 * cm))
    story.append(Paragraph(
        "LEGAL DISCLAIMER: This report is generated by an AI-based prediction system for informational "
        "purposes only. It does NOT constitute a medical diagnosis. Always consult a qualified "
        "healthcare professional before making any health-related decisions.",
        disclaimer_style,
    ))

    doc.build(story)
    pdf_bytes = buffer.getvalue()

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=healthsense_report_{prediction_id}.pdf"},
    )
